[package]
name = "game_data"
version = "0.1.0"
edition = "2021"

[dependencies]
math = { workspace = true }
time = { workspace = true }
serde = { workspace = true }
inputs = { workspace = true }
renderer = { workspace = true }


# TODO: These pollute other crates because they are erroring so their dependents can't compile enough to show errors
# inputs = { workspace = true }
# renderer = { workspace = true }
