# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
resolver = "2"
members = ["app", "core/*"]
exclude = ["core/utility", "core/arena"]

# TODO: inputs seems to not be getting proofed?
# Cause is any crate that relies on a crate that isn't compiling doesn't get compiled enought to check for errors

[workspace.dependencies]
eyre = "0.3.7"
app = { path = "app" }
game_data = { path = "core/game_data" }
storage = { path = "core/storage" }
math = { path = "core/math" }
time = { path = "core/time" }
nina = { git = "https://github.com/Barca545/Nina.git" }
inputs = { path = "core/inputs" }
renderer = { path = "core/renderer" }
windowing = { path = "core/windowing" }
thiserror = "1.0.48"
serde_json = "1.0"

[workspace.dependencies.sdl2]
version = "0.37"
features = ["raw-window-handle", "bundled"]

[workspace.dependencies.serde]
version = "1.0"
features = ["derive"]
