[workspace]
resolver = "2"
members = [
  "gl",
  "game_loop",
  "ecs",
  "view"
]

[workspace.dependencies]
ecs = {path ="ecs"}
view = {path ="view"}
game_loop = {path ="game_loop"}
gl = {path ="gl"}

[workspace.dependencies.sdl2]
version = "0.35.2"
default-features = false
features = ["image"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

