[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
gl = {workspace=true}
glfw = {workspace=true}
eyre = {workspace=true}
thiserror = {workspace=true}
cgmath = {workspace=true}
nalgebra-glm = {workspace=true}
image = {workspace=true}
winapi = {workspace=true}