[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = { workspace = true }
nina = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
time = { workspace = true }
sdl2 = { workspace = true }
game_data = { workspace = true }
renderer = { workspace = true }
windowing = { workspace = true }
math = { workspace = true }
