[package]
name = "ecs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = {workspace=true}
thiserror = {workspace=true}
sdl2 = {workspace=true}

[build-dependencies]
walkdir = "2.1"