[package]
name = "game_loop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = {workspace=true}
ecs = {workspace=true}
view = {workspace=true}
gl = {workspace=true}
eyre = {workspace=true}
thiserror = {workspace=true}